spring:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        "[show_sql]": true
        "[format_sql]": true
logging:
  level:
    org:
      hibernate:
        type: INFO

  
security:
  authentication:
    jwt:
      secret: secret   
      expiration: 86400